name: WordPress Cron Pinger

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Ping WordPress Site
        run: curl https://stone.maeilyogi.kr/wp-cron.php?doing_wp_cron
